v0.0.4

diff --git a/src/mmlong2 b/src/mmlong2
--- a/src/mmlong2
+++ b/src/mmlong2
@@ -17,7 +17,7 @@
 # bakta - directory, containing annotation results for genome bins
 
 # Pre-set default settings
-version="0.0.1"
+version="0.0.4"
 mode_workflow="Nanopore-only"
 stages_selected="OFF"
 extra_cov="OFF"
@@ -354,7 +354,7 @@ dir_semibin=/projects/microflora_danica/mmlong2/conda/SemiBin_1.4.0
 dir_graphmb=/projects/microflora_danica/mmlong2/conda/GraphMB_0.1.5
 dir_metabinner=/projects/microflora_danica/mmlong2/conda/MetaBinner_1.4.4
 dir_das_tool=/projects/microflora_danica/mmlong2/conda/DasTool_1.1.3
-dir_checkm=/projects/microflora_danica/mmlong2/conda/checkm2_0.1.3
+dir_checkm=/projects/microflora_danica/mmlong2/conda/CheckM2_1.0.0
 dir_quast=/projects/microflora_danica/mmlong2/conda/Quast_5.2.0
 dir_gunc=/projects/microflora_danica/mmlong2/conda/Gunc_1.0.5
 dir_bakta=/projects/microflora_danica/mmlong2/conda/Bakta_1.6.1
@@ -366,9 +366,11 @@ dir_gunc_db=/projects/microflora_danica/mmlong2/db/gunc_1.0.5/gunc_db_progenomes
 dir_bakta_db=/projects/microflora_danica/mmlong2/db/bakta_1.6.0/db
 dir_kaiju_db=/projects/microflora_danica/mmlong2/db/kaiju_db_nr_2022-03-10
 db_silva=/projects/microflora_danica/mmlong2/db/SILVA_138_SSURef_NR99_tax_silva.udb
+db_midas=/projects/microflora_danica/mmlong2/db/MiDAS5.0_20211221_FLASVs_w_sintax.fa
 
 # Make dataframe for software used
 echo "software,version" > $dir_work/tmp/dependencies.csv
+echo "mmlong2,$version" >> $dir_work/tmp/dependencies.csv
 echo "$(tr '/' ',' <<<"$MODUL_CONDA" | cut -f1 -d"-")" >> $dir_work/tmp/dependencies.csv
 echo "$(tr '_' ',' <<<"$(basename $dir_flye)")" >> $dir_work/tmp/dependencies.csv
 echo "$(tr '/' ',' <<<"$MODUL_BIOAWK" | cut -f1 -d"-")" >> $dir_work/tmp/dependencies.csv
@@ -1029,8 +1031,9 @@ else
 	
 	# Wrangle DAS Tool output
 	mkdir $dir_work/tmp/binning/bins
-	n=1 && for i in $dir_work/tmp/binning/das_tool/output_DASTool_bins/*.fa; do cp $i $dir_work/tmp/binning/bins/bin.${n}.fa && n=$(($n+1)) ; done
-	if [ -f $dir_work/tmp/binning/bins_c/cbins/bin.c1.fa ]; then rsync -avr $dir_work/tmp/binning/bins_c/cbins/*.fa $dir_work/tmp/binning/bins; fi
+	dir_work_=$(basename $dir_work | tr '_' '.' )
+	n=1 && for i in $dir_work/tmp/binning/das_tool/output_DASTool_bins/*.fa; do cp $i $dir_work/tmp/binning/bins/${dir_work_}.bin.${n}.fa && n=$(($n+1)); done
+	if [ -f $dir_work/tmp/binning/bins_c/cbins/bin.c1.fa ]; then n=1 && for i in $dir_work/tmp/binning/bins_c/cbins/*.fa; do cp $i $dir_work/tmp/binning/bins/${dir_work_}.bin.c${n}.fa && n=$(($n+1)); done; fi
 	cat $dir_work/tmp/binning/bins/*.fa > $dir_work/tmp/binning/contigs_binned.fasta
 	rsync -r $dir_work/tmp/binning/bins $dir_work/results/.
 	Fasta_to_Scaffolds2Bin.sh -i $dir_work/tmp/binning/bins -e fa > $dir_work/tmp/binning/contig_bin.tsv
@@ -1039,7 +1042,8 @@ else
 fi
 
 # Check if final output for linear contigs exists
-if [ ! -f $dir_work/tmp/binning/bins/bin.1.fa ]; then echo "ERROR in binning linear contigs. Aborting..." && exit 1; fi
+dir_work_=$(basename $dir_work | tr '_' '.' )
+if [ ! -f $dir_work/tmp/binning/bins/${dir_work_}.bin.1.fa ]; then echo "ERROR in binning linear contigs. Aborting..." && exit 1; fi
 
 # Early stoppage
 if [ $stages_selected == "binning" ]
@@ -1078,10 +1082,10 @@ else
 	echo "Bin feature metrics with Quast calculated at $(date "+%Y-%m-%d %H:%M:%S")" >> $dir_work/tmp/log.txt
 fi
 
-# Create directory for checkm output
+# Create directory for checkm2 output
 if [ -d "$dir_work/tmp/binning/checkm" ] 
 then
-    echo "WARNING: directory for CheckM output already exists" 
+    echo "WARNING: directory for CheckM2 output already exists" 
 else
     mkdir $dir_work/tmp/binning/checkm
 fi
@@ -1099,7 +1103,7 @@ else
 	if [ $threads_checkm -gt 40 ]; then threads_checkm=40; fi;
 	checkm2 predict -x .fa -i $dir_work/tmp/binning/bins -o $dir_work/tmp/binning/checkm -t $threads_checkm
 	source deactivate > /dev/null 2>&1
-	echo "Bin quality estimates with CheckM completed at $(date "+%Y-%m-%d %H:%M:%S")" >> $dir_work/tmp/log.txt
+	echo "Bin quality estimates with CheckM2 completed at $(date "+%Y-%m-%d %H:%M:%S")" >> $dir_work/tmp/log.txt
 fi
 
 # Create directory for gunc output
@@ -1117,6 +1121,7 @@ then
 else
 	module purge && module load $MODUL_CONDA > /dev/null 2>&1
 	source activate $dir_gunc > /dev/null 2>&1
+	export TMPDIR=$dir_tmp
 	gunc run --db_file $dir_gunc_db --input_dir $dir_work/tmp/binning/bins --out_dir $dir_work/tmp/binning/gunc --threads $threads --temp_dir $dir_tmp
 	source deactivate > /dev/null 2>&1
 	echo "Bin contamination estimates with Gunc completed at $(date "+%Y-%m-%d %H:%M:%S")" >> $dir_work/tmp/log.txt
@@ -1154,7 +1159,7 @@ then
 else
     mkdir $dir_work/tmp/binning/bakta
 fi
-bins_bakta_n=$(find $dir_work/tmp/binning/bakta -type f -name "bin*.gff3" | wc -l)
+bins_bakta_n=$(find $dir_work/tmp/binning/bakta -type f -name "*bin*.gff3" | wc -l)
 
 # Run Bakta
 if [ $bins_bakta_n -ge 1 ]
@@ -1164,17 +1169,19 @@ else
 	module load $MODUL_CONDA > /dev/null 2>&1
 	source activate $dir_bakta > /dev/null 2>&1
 	export dir_bakta_db=$dir_bakta_db
+	export bakta_tmp=$dir_tmp
 	cd $dir_work/tmp/binning
 	
-	splits=$(($threads / 4))
+	splits=$(($threads / 3))
 	if [ $splits -gt 25 ]; then splits=25; fi;
 	echo "Bakta parallelism set at $splits"
 	echo "Bakta parallelism set at $splits" >> $dir_work/tmp/log.txt
-	find $dir_work/tmp/binning/bins -type f -name "*.fa" -printf '%f\n' | sed 's/...$//' | xargs -i --max-procs=$splits bash -c 'bakta --compliant --db $dir_bakta_db --prefix {} --locus {} --keep-contig-headers --output bakta/{} --tmp-dir /user_data/mase/general/tmp --threads 4 bins/{}.fa --skip-crispr'
+	find $dir_work/tmp/binning/bins -type f -name "*.fa" -printf '%f\n' | sed 's/...$//' | xargs -i --max-procs=$splits bash -c 'bakta --compliant --db $dir_bakta_db --prefix {} --output bakta/{} --keep-contig-headers --tmp-dir $bakta_tmp --threads 3 bins/{}.fa --skip-crispr'
 	echo "Bin annotation with Bakta completed at $(date "+%Y-%m-%d %H:%M:%S")" >> $dir_work/tmp/log.txt
 	source deactivate > /dev/null 2>&1
+	
 	cd $dir_work
-	bins_bakta_n=$(find $dir_work/tmp/binning/bakta -type f -name "bin*.gff3" | wc -l)
+	bins_bakta_n=$(find $dir_work/tmp/binning/bakta -type f -name "*bin*.gff3" | wc -l)
 	rsync -avr $dir_work/tmp/binning/bakta $dir_work/results/. > /dev/null 2>&1
 fi
 
@@ -1248,13 +1255,15 @@ else
 fi
 
 # Classify 16S rRNA
-if [ -f "$dir_work/tmp/silva_16s.tsv" ] 
+if [ -f "$dir_work/tmp/midas_16s.tsv" ] 
 then
     echo "16S rRNA classification results already exist. Skipping..." 
 else
     grep -A1 ">16S" $dir_work/results/rRNA.fa > $dir_work/tmp/16s.fa
-	usearch11 -usearch_global $dir_work/tmp/16s.fa -db $db_silva -strand both -id 0.7 -maxaccepts 0 -maxrejects 0 -top_hit_only -threads $threads -blast6out $dir_work/tmp/silva_16s.tsv
-	echo "Classification of 16S rRNA sequences to Silva database completed at $(date "+%Y-%m-%d %H:%M:%S")" >> $dir_work/tmp/log.txt
+	usearch11 -orient $dir_work/tmp/16s.fa -db $db_silva -fastaout $dir_work/tmp/16s_oriented.fa
+	usearch11 -usearch_global $dir_work/tmp/16s_oriented.fa -db $db_silva -strand plus -id 0.7 -maxaccepts 0 -maxrejects 0 -top_hit_only -threads $threads -blast6out $dir_work/tmp/silva_16s.tsv
+	usearch11 -usearch_global $dir_work/tmp/16s_oriented.fa -db $db_midas -strand plus -id 0.7 -maxaccepts 0 -maxrejects 0 -top_hit_only -threads $threads -blast6out $dir_work/tmp/midas_16s.tsv
+	echo "Classification of 16S rRNA sequences completed at $(date "+%Y-%m-%d %H:%M:%S")" >> $dir_work/tmp/log.txt
 fi
 
 # Early stoppage
@@ -1494,17 +1503,18 @@ cp $dir_work/tmp/kaiju/kaiju.out.names $dir_work/tmp/processing
 cp $dir_work/tmp/binning/contig_bin.tsv $dir_work/tmp/processing
 cp $dir_work/tmp/binning/gtdb/classify/gtdbtk.bac120.summary.tsv $dir_work/tmp/processing
 cp $dir_work/tmp/silva_16s.tsv $dir_work/tmp/processing
+cp $dir_work/tmp/midas_16s.tsv $dir_work/tmp/processing
 cp $dir_work/tmp/binning/medaka_var/medaka_var_bins.tsv $dir_work/tmp/processing
 cp $dir_work/tmp/binning/medaka_var/medaka_var.csv $dir_work/tmp/processing
 cp $dir_work/tmp/binning/bakta_stats.csv $dir_work/tmp/processing
 
 cut -f1,14,15,16,17,18,20,23 $dir_work/tmp/binning/quast/transposed_report.tsv | sed 1d - > $dir_work/tmp/processing/quast.tsv
-cut -f1,2,3 $dir_work/tmp/binning/checkm/quality_report.tsv | sed 1d - > $dir_work/tmp/processing/checkm.tsv
+cut -f1,2,3,6 $dir_work/tmp/binning/checkm/quality_report.tsv | sed 1d - > $dir_work/tmp/processing/checkm.tsv
 cut -f1,9,13 $dir_work/tmp/binning/gunc/GUNC.progenomes_2.1.maxCSS_level.tsv > $dir_work/tmp/processing/gunc.tsv
 
 # First checkpoint for file processing
 files_count=$(ls $dir_work/tmp/processing | wc -l)
-if [ $files_count -eq 19 ]                                                                                                                           
+if [ $files_count -eq 20 ]                                                                                                                           
 then
     echo "Initating processing of results from previous stages..."
 	echo "Input for data aggregation found at $(date "+%Y-%m-%d %H:%M:%S")" >> $dir_work/tmp/log.txt
@@ -1563,7 +1573,7 @@ fi
 
 # Second checkpoint for file processing
 files_count=$(ls $dir_work/tmp/processing | wc -l)
-if [ $files_count -eq 21 ]                                                                                                                      
+if [ $files_count -eq 22 ]                                                                                                                      
 then
     echo "Proceeding to dataframe generation..." 
 else
@@ -1605,7 +1615,7 @@ quast=read.delim("quast.tsv", sep="\t", header=F)
 colnames(quast) <- c("bin","contigs","Longest_contig_bp","Genome_size_bp","GC","N50_bp","auN","N_per_100kb")
 
 checkm=read.delim("checkm.tsv", sep="\t", header=F)
-colnames(checkm) <- c("bin","Completeness","Contamination")
+colnames(checkm) <- c("bin","Completeness","Contamination","Coding_density")
 
 gunc=read.delim("gunc.tsv", sep="\t", header=T)
 colnames(gunc) <- c("bin","gunc_contamination","gunc_status")
@@ -1627,10 +1637,40 @@ silva=silva[c("X3","V2","V3")]
 colnames(silva) <- c("contig","silva_16s","identity")
 silva=merge(silva,bin_contig, by="contig")
 silva$bin <- as.factor(silva$bin)
-silva <- do.call(rbind, lapply(split(silva,silva$bin), function(x) {return(x[which.max(x$identity),])}))
-silva <- silva[c("bin","silva_16s")]
-colnames(silva) <- c("bin","silva_taxonomy")
-silva <- silva[!duplicated(silva$bin),]
+
+silva_agr <- aggregate(silva$bin, by=list(silva$bin, silva$silva_16s), FUN=length)
+silva_agr$sub <- paste(silva_agr$Group.1,silva_agr$Group.2,sep="_")
+silva_agr <- do.call(rbind, lapply(split(silva_agr,silva_agr$Group.1), function(x) {return(x[which.max(x$x),])}))
+colnames(silva_agr) <- c("bin","silva_taxonomy","n","id")
+
+silva$id <- paste(silva$bin,silva$silva_16s,sep="_")
+silva_tmp <- silva[c("id","identity")]
+silva_tmp <- do.call(rbind, lapply(split(silva_tmp,silva$id), function(x) {return(x[which.max(x$identity),])}))
+silva <- merge(silva_agr,silva_tmp, by="id")
+
+silva <- silva[c("bin","silva_taxonomy","identity")]
+colnames(silva) <- c("bin","silva_classification","silva_identity")
+
+# Wrangle midas taxonomy data 
+midas=read.delim("midas_16s.tsv", sep="\t", header=F)
+midas=cbind(midas, data.frame(do.call('rbind', strsplit(as.character(midas$V1),':',fixed=TRUE))))
+midas=midas[c("X3","V2","V3")]
+colnames(midas) <- c("contig","midas_16s","identity")
+midas=merge(midas,bin_contig, by="contig")
+midas$bin <- as.factor(midas$bin)
+
+midas_agr <- aggregate(midas$bin, by=list(midas$bin, midas$midas_16s), FUN=length)
+midas_agr$sub <- paste(midas_agr$Group.1,midas_agr$Group.2,sep="_")
+midas_agr <- do.call(rbind, lapply(split(midas_agr,midas_agr$Group.1), function(x) {return(x[which.max(x$x),])}))
+colnames(midas_agr) <- c("bin","midas_taxonomy","n","id")
+
+midas$id <- paste(midas$bin,midas$midas_16s,sep="_")
+midas_tmp <- midas[c("id","identity")]
+midas_tmp <- do.call(rbind, lapply(split(midas_tmp,midas$id), function(x) {return(x[which.max(x$identity),])}))
+midas <- merge(midas_agr,midas_tmp, by="id")
+
+midas <- midas[c("bin","midas_taxonomy","identity")]
+colnames(midas) <- c("bin","midas_classification","midas_identity")
 
 # Load and wrangle Kaiju data
 kaiju=read.delim("kaiju.out.names", sep="\t", header=F)
@@ -1667,6 +1707,7 @@ bins <- merge(bins,checkm, by="bin", all=TRUE)
 bins <- merge(bins,gunc, by="bin", all=TRUE)
 bins <- merge(bins,gtdb, by="bin", all=TRUE)
 bins <- merge(bins,silva, by="bin", all=TRUE)
+bins <- merge(bins,midas, by="bin", all=TRUE)
 
 general$mags_workflow_name <- name$V1
 general$mags_workflow_date <- name$V2
